export const PostData = [
    {
        id: 1,
        username: "Hà Văn Được",
        date: "5 phút trước",
        title: "Amber",
        desc: "",
        photo: "assets/post/Amber.png",
        tag: "#amber",
        like: 87,
        comment: 9,
        share: 10,
        view: "10k",
    },
    {
        id: 2,
        username: "Hà Văn Được",
        date: "10 phút trước",
        title: "Ayaka",
        desc: "",
        photo: "assets/post/Ayaka.jpg",
        tag: "#ayaka",
        like: 99,
        comment: 20,
        share: 10,
        view: "10k",
    },
    {
        id: 3,
        username: "Hà Văn Được",
        date: "15 phút trước",
        title: "Babara",
        desc: "",
        photo: "assets/post/Babara.png",
        tag: "#babara",
        like: 45,
        comment: 23,
        share: 10,
        view: "10k",
    },
    {
        id: 4,
        username: "Hà Văn Được",
        date: "20 phút trước",
        title: "Eula",
        desc: "",
        photo: "assets/post/Eula.jpg",
        tag: "#eula",
        like: 209,
        comment: 50,
        share: 10,
        view: "10k",
    },
    {
        id: 5,
        username: "Hà Văn Được",
        date: "25 phút trước",
        title: "Kokomi",
        desc: "",
        photo: "assets/post/Kokomi.jpg",
        tag: "#kokomi",
        like: 167,
        comment: 26,
        share: 10,
        view: "10k",
    },
    {
        id: 6,
        username: "Hà Văn Được",
        date: "30 phút trước",
        title: "Yoimiya",
        desc: "",
        photo: "assets/post/Yoimiya.png",
        tag: "#yoimiya",
        like: 112,
        comment: 46,
        share: 10,
        view: "10k",
    },
];
