export const PostData = [
    {
        id: 1,
        username: "Hà Văn Được",
        date: "5 phút trước",
        title: "Amber",
        desc: "",
        img: "images/post/Amber.png",
        tag: "#amber",
        favourites: 87,
        comment: 2,
        share: 10,
        view: "10k",
    },
    {
        id: 2,
        username: "Hà Văn Được",
        date: "10 phút trước",
        title: "Ayaka",
        desc: "",
        photo: "/images/post/Ayaka.jpg",
        tag: "#ayaka",
        countfavourite: 99,
        countComment: 20,
        countShare: 10,
        view: "10k",
    },
    {
        id: 3,
        username: "Hà Văn Được",
        date: "15 phút trước",
        title: "Babara",
        desc: "",
        photo: "/images/post/Babara.png",
        tag: "#babara",
        countfavourite: 45,
        countComment: 23,
        countShare: 10,
        view: "10k",
    },
    {
        id: 4,
        username: "Hà Văn Được",
        date: "20 phút trước",
        title: "Eula",
        desc: "",
        photo: "/images/post/Eula.jpg",
        tag: "#eula",
        countfavourite: 209,
        countComment: 50,
        countShare: 10,
        view: "10k",
    },
    {
        id: 5,
        username: "Hà Văn Được",
        date: "25 phút trước",
        title: "Kokomi",
        desc: "",
        photo: "/images/post/Kokomi.jpg",
        tag: "#kokomi",
        countfavourite: 167,
        countComment: 26,
        countShare: 10,
        view: "10k",
    },
    {
        id: 6,
        username: "Hà Văn Được",
        date: "30 phút trước",
        title: "Yoimiya",
        desc: "",
        photo: "/images/post/Yoimiya.png",
        tag: "#yoimiya",
        countfavourite: 112,
        countComment: 46,
        countShare: 10,
        view: "10k",
    },
];
